# .travis.yml

sudo: required
dist: trusty
branches:
  only:
    - develop
language: node_js
node_js:
  - '7.6.0'

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
- npm install -g @angular/cli
- npm install -g karma
- npm install
- ng build

script: 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then ng test --watch=false; fi'

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  on:
    branch: develop
    condition: $TRAVIS_PULL_REQUESTION = false
  local_dir: dist
  target_branch: master


